### PR TITLE
[master] platform.mk: Update shipping API level

### PR DESCRIPTION
**Pull request by bartcubbins**
Kumano devices has been commercially launched on P,
hence first API level is 28.

Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>

### CODE REVIEW

**Comment by MarijnS95** [comment]
How about using the `product_launched_with` macro, just like we do for a 64-bit platform?
```
$(call inherit-product, $(SRC_TARGET_DIR)/product/product_launched_with_p.mk)
```

**Comment by bartcubbins** [comment]
yes, I thought to use this way for all devices:)

**Comment by bartcubbins** [comment]
will PR this weekend

**Comment by MarijnS95** [comment]
[I thought the same](https://github.com/MarijnS95/device-sony-tama/commit/85f67ed9848838ace4034c263a99564dd8a53ea1) :grin: 

There are other "generic" (iirc?) targets that can set up standard properties for us, for example for Treble and VNDK compatibility. Maybe worth investigating those, but on the other hand they may make it harder to trace back issues with future Android updates.

**Comment by bartcubbins** [comment]
:smiley:
but it seems to me that it is better to keep this flag in the device repository instead of platform one, since we have devices on the same platform but with a different Android version at launch. e.g. maple and poplar

**Comment by MarijnS95** [comment]
Let's determine that per platform/device.

I anyway do not really care about the official stock release that the phone shipped with. Instead I am much more interested in having a version that represents the current state of SODP. After all, this API level switches on nice features for validation and correctness (to get proper Treble/VNDK) and doesn't have much relation to stock if at all (okay, missing vendor partition on legacy devices, AB, etc). But as long as that's in check, we might as well bump the versions up.
Instead we have to manually `_OVERRIDE := true` for all these versions. But since we already have that there's not much point bumping the API as well.

**Comment by bartcubbins** [comment]
I completely agree with you

**Pull request merged**
