### PR TITLE
[KUMANO] platform: Set optimal audio offload buffer size

### PR DESCRIPTION
**Pull request by kholk**
The optimal offload buffer size is 32kb on SM8150.

### CODE REVIEW

**Comment by MarijnS95** [comment]
The default is 32kb, too :joy: 

I was initially surprised when you said kilobit, as that means a buffer is 1/4th of a second on a 128kbps mp3 file, which means way more wakeups than I expected. Fortunately, looking at `calloc(1,out->compr_config.fragment_size)` this is in kilobyte :grimacing:, so one buffer would be roughly 2 seconds.

Then I don't have the time to dig further into the code, but `#define COMPRESS_OFFLOAD_NUM_FRAGMENTS 4` indicates that four of those buffers, for a total of 8 seconds, can concurrently be in-flight. Of course they should be filled well in time so the AP still has to wake up way more often than that, but once every 2s (4s on Ningles, which has a 64kB buffer for some reason...) doesn't seem too bad.

**Comment by kholk** [comment]
Yes I know it is the default value, but you don't know when they will change this next time. This default value was changed many many times in the audio hal during time.... :p

**Comment by MarijnS95** [comment]
Sure... but then should we set some sane default for Tama, Yoshino and Seine, too?

**Comment by kholk** [comment]
I said it in the chat... I asked to cherry pick this exact commit to the platforms that you've mentioned... The safe default is 32 for all..

**Comment by MarijnS95** [comment]
> This default value was changed many many times in the audio hal during time....

Just want to say this hasn't changed since the inception of `hal: Add support for PCM in offload path` in the 2014...

Anyway, for completeness:
```
  Duration: 01:27:11.88, bitrate: 137 kb/s
    Stream #0:0: Audio: aac (LC), 48000 Hz, stereo, fltp, 137 kb/s
```
Logs from the compress offload codepath fill buffer at a regular interval of 2s :grin:

**Pull request merged**
